name: Aria2

on: workflow_dispatch

jobs:
  job_1:
    name: Aria2-x64
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          git clone https://github.com/zwypfdsj/docker.git /opt/docker
          cd /opt/docker/aria2
          docker build -t aria2-x64 - < Dockerfile.x64
          id=$(docker create aria2-x64)
          docker cp $id:/aria2/src/aria2c /opt/docker/aria2/aria2c-x64
          docker rm -v $id

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: aria2c-x64
          path: /opt/docker/aria2/aria2c-x64

  job_2:
    name: Aria2-musl
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          git clone https://github.com/zwypfdsj/docker.git /opt/docker
          cd /opt/docker/aria2
          docker build -t aria2-musl - < Dockerfile.musl
          id=$(docker create aria2-musl)
          docker cp $id:/aria2/src/aria2c /opt/docker/aria2/aria2c-musl
          docker rm -v $id

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: aria2c-musl
          path: /opt/docker/aria2/aria2c-musl

  job_3:
    name: Aria2-win
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          git clone https://github.com/zwypfdsj/docker.git /opt/docker
          cd /opt/docker/aria2
          docker build -t aria2-win - < Dockerfile.win
          id=$(docker create aria2-win)
          docker cp $id:/aria2/src/aria2c.exe /opt/docker/aria2/aria2c-win.exe
          docker rm -v $id

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: aria2c-win
          path: /opt/docker/aria2/aria2c-win.exe

  job_4:
    name: Aria2-mingw
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          git clone https://github.com/zwypfdsj/docker.git /opt/docker
          cd /opt/docker/aria2
          docker build -t aria2-mingw - < Dockerfile.mingw
          id=$(docker create aria2-mingw)
          docker cp $id:/aria2/src/aria2c.exe /opt/docker/aria2/aria2c-mingw.exe
          docker rm -v $id

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: aria2c-mingw
          path: /opt/docker/aria2/aria2c-mingw.exe

  job_5:
    name: Aria2-gcc
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          git clone https://github.com/zwypfdsj/docker.git /opt/docker
          cd /opt/docker/aria2
          docker build -t aria2-gcc - < Dockerfile.gcc
          id=$(docker create aria2-gcc)
          docker cp $id:/aria2/src/aria2c /opt/docker/aria2/aria2c-gcc
          docker rm -v $id

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: aria2c-gcc
          path: /opt/docker/aria2/aria2c-gcc