name: Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y git
          git clone https://github.com/zwypfdsj/docker.git /opt/docker

      - name: V2Ray
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/v2ray
          file: /opt/docker/v2ray/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/v2ray
            ghcr.io/zwypfdsj/v2ray:latest

      - name: XRay
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/xray
          file: /opt/docker/xray/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/xray
            ghcr.io/zwypfdsj/xray:latest

      - name: Caddy
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/caddy
          file: /opt/docker/caddy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/caddy
            ghcr.io/zwypfdsj/caddy:latest

      - name: RSSBot
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/rssbot
          file: /opt/docker/rssbot/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/rssbot
            ghcr.io/zwypfdsj/rssbot:latest

      - name: nezha-dashboard
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/nezha
          file: /opt/docker/nezha/Dockerfile.dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/nezha:dashboard
            ghcr.io/zwypfdsj/nezha-dashboard:latest

      - name: nezha-agent
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/nezha
          file: /opt/docker/nezha/Dockerfile.agent
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/nezha:agent
            ghcr.io/zwypfdsj/nezha-agent:latest

      - name: Aria2
        uses: docker/build-push-action@v2
        with:
          context: /opt/docker/aria2
          file: /opt/docker/aria2/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zwypfdsj/aria2
            ghcr.io/zwypfdsj/aria2:latest