name: KeePassDX

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y git
          git clone https://github.com/Kunzisoft/KeePassDX.git /opt/keepassdx

      - name: Build
        run: |
          cd /opt/keepassdx
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: /opt/keepassdx/app/build/outputs/apk/libre/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name : Upload
        uses: actions/upload-artifact@v3
        with:
          name: KeePassDX
          path: ${{steps.sign.outputs.signedReleaseFile}}