name: Legado

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y git
          git clone https://github.com/gedoor/legado.git /opt/legado
          echo "ojbk">/opt/legado/app/src/main/assets/18PlusList.txt

      - name: Build
        run: |
          cd /opt/legado
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: /opt/legado/app/build/outputs/apk/app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name : Upload
        uses: actions/upload-artifact@v2
        with:
          name: legado
          path: ${{steps.sign.outputs.signedReleaseFile}}