name: Legado

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y git

      - name: Init Code
        run: |
          git clone https://github.com/gedoor/legado.git /opt/legado
          echo "ojbk">/opt/legado/app/src/main/assets/18PlusList.txt

      - name: Build
        run: |
          cd /opt/legado
          chmod +x gradlew
          ./gradlew assembleRelease

      - name : Upload
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: legado
          path: /opt/legado/app/build/outputs/apk/app/release