name: V2Ray

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y git
          git clone https://github.com/v2fly/v2ray-core.git /opt/v2ray-core

      - name: Build
        run: |
          cd /opt/v2ray-core
          export CODENAME=$(git rev-parse --short HEAD)
          export BUILDNAME=$(date '+%Y%m%d-%H%M%S')
          export VERSIONTAG=$(git describe --abbrev=0 --tags)
          export LDFLAGS="-s -w -buildid= -X github.com/v2fly/v2ray-core/v5.codename=${CODENAME} -X github.com/v2fly/v2ray-core/v5.build=${BUILDNAME} -X github.com/v2fly/v2ray-core/v5.version=${VERSIONTAG}"
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o /opt/v2ray-amd64 -trimpath -ldflags "$LDFLAGS" ./main
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -o /opt/v2ray-arm64 -trimpath -ldflags "$LDFLAGS" ./main
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -o /opt/v2ray.exe -trimpath -ldflags "$LDFLAGS" ./main

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v2ray-windows-x64
          path: |
            /opt/v2ray.exe

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v2ray-linux-x64
          path: |
            /opt/v2ray-amd64

      - name : Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v2ray-linux-arm64
          path: |
            /opt/v2ray-arm64